[package]
name = "keycontainerex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
dirs = "5.0.1"
keepass = { version = "0.6.1", features = ["save_kdbx4"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.4"
keycontainerex_backend = { path = "../lib" }
